// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
// Source: user_rpc.proto

package server

import (
	"context"

	"server/yu_user/user_rpc/internal/logic"
	"server/yu_user/user_rpc/internal/svc"
	"server/yu_user/user_rpc/types/user_rpc"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user_rpc.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) UserCreate(ctx context.Context, in *user_rpc.UserCreateRequest) (*user_rpc.UserCreateResponse, error) {
	l := logic.NewUserCreateLogic(ctx, s.svcCtx)
	return l.UserCreate(in)
}

func (s *UserServer) UserInfo(ctx context.Context, in *user_rpc.UserInfoRequest) (*user_rpc.UserInfoResponse, error) {
	l := logic.NewUserInfoLogic(ctx, s.svcCtx)
	return l.UserInfo(in)
}
